import JSPProblem.Definitions
import JSPProblem.ColorClass
import JSPProblem.Counting
import JSPProblem.Paths
import JSPProblem.Ghost
import JSPProblem.Construction
import JSPProblem.Main
import JSPProblem.Restriction
import JSPProblem.Extremal
import JSPProblem.Slack
import JSPProblem.Singles
import JSPProblem.Tables
import JSPProblem.Search
import JSPProblem.Distinct
import JSPProblem.FastSearch
import JSPProblem.VertexSearch
import JSPProblem.QuadEnum
import JSPProblem.LeafFree
import JSPProblem.Local
import JSPProblem.Classwise
import JSPProblem.Criterion
import JSPProblem.Design
import JSPProblem.Triangles
import JSPProblem.Leftover
import JSPProblem.Second
import JSPProblem.Stage2
import JSPProblem.StarColour
import JSPProblem.Cross
import JSPProblem.Slot
import JSPProblem.First
import JSPProblem.Fam
import JSPProblem.Partial
import JSPProblem.Hyper
import JSPProblem.Spoil
import JSPProblem.Edge
import JSPProblem.Surplus
import JSPProblem.Census
import JSPProblem.Seven
import JSPProblem.Product
import JSPProblem.Amplify
import JSPProblem.Block
import JSPProblem.Cover
import JSPProblem.Sharp
import JSPProblem.Strict
import JSPProblem.Apex
import JSPProblem.BlockCol
import JSPProblem.Alt
import JSPProblem.Quad
import JSPProblem.Pairs
import JSPProblem.Moment
import JSPProblem.Pack
